language: android
android:
  components:
    - platform-tools
    - tools
    - build-tools-23.0.2
    - android-23

before_install:
  - chmod +x dcapp/gradlew

script: 
  - cd dcapp
  - gradle build
  - chmod +x ./gradlew
  - ./gradlew test
