language: android
android:
  components:
    - platform-tools
    - tools
    - build-tools-23.0.2
    - android-23
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository

before_script:
    - export CHROME_BIN=chromium-browser
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - cd dch
    - npm install karma
    - npm install karma-firefox-launcher
    - npm install karma-chrome-launcher
    - npm install karma-ng-html2js-preprocessor
    - npm install karma-jasmine
    - npm install jasmine-core
    - npm install angular-mocks
    - npm install mocha
    - npm install chai
    - npm install should
    - npm install assert
    - npm install supertest
    - npm install express
    - npm install mongoose
    - npm install mongodb
    - npm install mqtt
    - cd ..

script: 
  - cd dcapp && gradle build -q
  - cd ../dch && node ./dch.js &
  - npm test

